---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    adminPassword: AgAFaONBZBDU/J1Sq/bpzeEgRIMd2JqUCtZ5TMTUnE7fI33odaBiTy9KU7WoGd6lqJr2W6uEPicWQ7YGAYxE0JlX62rkohahE7rJbi6NXVO8sCWQOasY+RhVJdJz2+V83RPpsf8gWFBgpYyOPU5sOUUhSj7D5aqiI/vvbI2xMAwKyJAhJ1F2Za/1MIcZwsKBw0rl64oCXJwXDX9znWxP+V1pHoJwwvO49x8DAIFb1qYv0q9wGK4kCVxQ8ct10FADwSrjb784gajQlIHrCixrW66HrePZGpi/5lLV3gBP9OW4s05qlXi+CcEapMrDe/nL3cNho6l1IFQ8QsANLz2SOWO7qQHWab0SK7PHjKXM6YBrQLY6FOrTRpM8yncxyY3PTBof9Lf7KsyzQBO7Cn+gxT4yTQCqXT/xvFRgR+wV6nK3/xo5caODchTcijvwlpBp8q0fOC/pK+dsdp2pKYCJCzoqSHYUSKie0597dPB8fttpnCkHhTqVOcvsyl2U04AYDHWbY/53y2JY0xbpWX7ibAyCy/CA2rzLXxt/vguIjJ/JaHWW9O54eBH5p5qHjmrPEWHaGqRfHDBb6a/8V7qhNAjlV76VDMvpg1J1aZ8FqhSJhbjjmzd367uJMNoQD7OXE/B/KQbpOxhywxk4w+eu80W4WcpSpxBQ3gFvgQC7coGRTaeSkI88IYgo+KB0Q0TZiDDFj9Vd0w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
