prometheus:
  replicas: 1
  image: prom/prometheus:latest

grafana:
  replicas: { { .Values.grafana.replicas } }
  image: { { .Values.grafana.image } }
  adminPassword: { { .Values.grafana.adminPassword | quote } }
  storage: { { .Values.grafana.storage } }

nodeExporter:
  image: prom/node-exporter:latest
