---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    adminPassword: AgA+heB4JH0Upx561n69+9dgEk6V2SPwgunsVxktUqgyJNP/r0v28hxyaARptLDTJTK/pECewwV9SwhNB6R+HFyu+M93mzBiH6FqgvaGDG7Ug7fQcipCSKIGJN+GvK+5Lb7JkkMUDClayf2eV1VEGE2zyVQMi/E6OSmeMC45DgMzAG3Yao8oY95umpNcHCJhIeISkcOEeLASptAdkQhlbUuwfczKV3Unk1atGOqy3dGD88seIpazaMg9VU102CmK89WuulQ/jy8NVVU5kFU9ERkABdEOqS4tBUduN1c13q3+GOcjw6NRdQWPUBs96ExhAlWDUphXArlKMmqR6cmbmyDKOyQCi3X/Yxg/g+obppDbv2fMllnIE87tdL3z7azHihQCPyo4cZI6Ba+Ey5nxuVKoo9ObhZ4Fx34pqSD8tgnQ1Tm3W79hy5k+Wsh+clTwaRctCDxWZcWnvm5GrPbHcE5PueEIx4WOtKFziQY/PMEv/4GnNzuLTnHgXnfOsWTMMO4spHjs7t3t6W2EhUE8jF7alJEU0D8VC5Wt+Fk9e+jhJbRopffy8Vjr2wVZe5wwOmzY0J+BwU6m4k9fa1ikfsityIKB1GwKpzd3U94j/TTlP6VT+yZuN7ALxC6Xpiysi600O8p9PRa5HAPxoW7U/5l3LV4YquiX//sZF1fV8uD0wCym7n0lI1u3hjLS9gQHD0iqYY6vEg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
