name: Helm Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm chat
        run: helm lint k8s/charts/monitoring

      - name: Template Helm chart
        run: helm template monitoring k8s/charts/monitoring